/* EHRENMARKT – CLAN-BUCHHALTUNG V1.0
   Manuelle Buchhaltung. Keine Pop-ups/Toasts. Unveränderbare Buchungen.
   Voraussetzung: ../supabase.js stellt window.supabaseClient bereit.
*/
(()=>{'use strict';
const T={book:'buchhaltung_buchungen',save:'buchhaltung_sparkonto',orders:'buchhaltung_auftragsabrechnungen',workers:'buchhaltung_auftragsarbeiter',employees:'employees',protocol:'buchhaltung_protokoll',cash:'buchhaltung_kassenabgleich',don:'buchhaltung_spenden',pay:'buchhaltung_auszahlungen',loan:'buchhaltung_darlehen',rate:'buchhaltung_darlehen_raten',warn:'buchhaltung_darlehen_mahnungen'};
const S={user:null,me:null,employees:[],book:[],savings:[],orders:[],workers:[],protocol:[],cash:[],don:[],pay:[],loans:[],rates:[],warnings:[],pending:null};
const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])), n=x=>{let v=Number(String(x??'').replace(',','.'));return Number.isFinite(v)?v:0}, money=x=>`${n(x).toLocaleString('de-DE',{minimumFractionDigits:0,maximumFractionDigits:2})} $`, dt=x=>x?new Date(x).toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'}):'—', today=()=>new Date().toISOString().slice(0,10);
function db(){return window.supabaseClient||window.supabase||null}
function status(msg,type='info'){let e=$('status');e.className='status show '+type;e.textContent=msg}
function clearStatus(){let e=$('status');e.className='status'}
function rank(){return S.me?.rang||''} function isSL(){return rank()==='Stadtleitung'} function isLE(){return rank()==='Leitung'||isSL()}
async function q(table,op='select',payload){let d=db();if(!d)throw Error('Supabase-Client nicht gefunden. Prüfe ../supabase.js.');if(op==='select'){let r=await d.from(table).select('*');if(r.error)throw r.error;return r.data||[]}if(op==='insert'){let r=await d.from(table).insert(payload).select();if(r.error)throw r.error;return r.data||[]}throw Error('DB-Operation nicht unterstützt')}
async function auth(){let d=db();if(!d)throw Error('Supabase-Client nicht gefunden.');let {data,error}=await d.auth.getUser();if(error)throw error;S.user=data.user;if(!S.user)throw Error('Nicht angemeldet.');let es=await q(T.employees);S.employees=es;S.me=es.find(x=>x.user_id===S.user.id)||null;if(!S.me)throw Error('Kein Mitarbeiterprofil für den angemeldeten Benutzer gefunden.');$('currentUser').textContent=S.me.name||S.user.email||'Unbekannt';$('currentRank').textContent=`Rang: ${S.me.rang||'nicht gesetzt'}`}
async function load(){let jobs=Object.entries(T).filter(([k])=>!['employees'].includes(k)).map(async([k,t])=>{try{S[k]=await q(t)}catch(e){S[k]=[];console.warn(t,e)}});await Promise.all(jobs);renderAll()}
function val(id){return $(id)?.value||''}
function requirePositive(id,label){let v=n(val(id));if(v<=0)throw Error(`${label} muss größer als 0 sein.`);return v}
function fmtPerson(id){let e=S.employees.find(x=>x.user_id===id);return e?.name||id||'—'}
function currentName(){return S.me?.name||S.user?.email||'Unbekannt'}
function addProtocol(type,desc,amount=0){return q(T.protocol,'insert',{user_id:S.user.id,aktion:type,beschreibung:desc,betrag:amount,created_at:new Date().toISOString()}).catch(()=>{})}
function confirmBook(text,fn){S.pending=fn;$('confirmText').textContent=text;$('confirmModal').classList.add('open')}
async function runPending(){let f=S.pending;S.pending=null;$('confirmModal').classList.remove('open');if(!f)return;try{clearStatus();await f();await load();status('Buchung wurde endgültig gespeichert.','success')}catch(e){console.error(e);status(e.message||'Buchung konnte nicht gespeichert werden.','error')}}
function nav(){document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.navbtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$('page-'+b.dataset.page).classList.add('active');$('sidebar').classList.remove('open')});$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open')}
function employeeOptions(select,includeSelf=true){let list=S.employees.filter(e=>e.is_active!==false);$(select).innerHTML=list.map(e=>`<option value="${esc(e.user_id)}" ${includeSelf&&e.user_id===S.user.id?'selected':''}>${esc(e.name||e.user_id)}${e.rang?` – ${esc(e.rang)}`:''}</option>`).join('')}
function orderWorkerRows(){return [...document.querySelectorAll('.workerRow')].map(r=>({employee_id:r.querySelector('select').value,salary:n(r.querySelector('input').value)}))}
function addWorker(){let box=$('orderWorkers'),row=document.createElement('div');row.className='workerRow';row.style='display:grid;grid-template-columns:1fr 130px 35px;gap:6px;margin-top:7px';row.innerHTML=`<select></select><input type="number" min="0" step="0.01" placeholder="Lohn"><button class="secondary" type="button">×</button>`;box.appendChild(row);employeeOptionsTemp(row.querySelector('select'));row.querySelector('button').onclick=()=>row.remove();orderPreview()}
function employeeOptionsTemp(sel){sel.innerHTML=S.employees.filter(e=>e.is_active!==false).map(e=>`<option value="${esc(e.user_id)}">${esc(e.name||e.user_id)}</option>`).join('')}
function orderPreview(){let a=n(val('orderAmount')),c=n(val('orderClan')),w=orderWorkerRows().reduce((s,x)=>s+x.salary,0),r=a-w-c;$('orderPreview').innerHTML=`Auftrag: <b>${money(a)}</b><br>Löhne: ${money(w)}<br>Clan-Anteil: ${money(c)}<br>Restbetrag: <b class="${r<0?'red':'green'}">${money(r)}</b>`}
async function saveOrder(){let no=val('orderNo'),title=val('orderTitle'),a=requirePositive('orderAmount','Auftragssumme'),c=n(val('orderClan')),ws=orderWorkerRows();if(!no||!title)throw Error('Auftragsnummer und Auftragstitel sind Pflichtfelder.');if(ws.some(x=>x.salary<0))throw Error('Ungültiger Mitarbeiterlohn.');if(a-ws.reduce((s,x)=>s+x.salary,0)-c<0)throw Error('Löhne + Clan-Anteil überschreiten die Auftragssumme.');confirmBook('Der Auftrag wird sofort als vollständig bezahlt und abgeschlossen gespeichert. Danach ist keine Änderung oder Stornierung möglich.',async()=>{let o=(await q(T.orders,'insert',{auftragsnummer:no,titel:title,auftragssumme:a,clan_anteil:c,gebucht_von:S.user.id,abschluss_at:new Date().toISOString()}))[0];for(const w of ws)await q(T.workers,'insert',{auftrag_id:o.id,mitarbeiter_id:w.employee_id,gehalt:w.salary});await addProtocol('Auftrag',`Auftrag ${no} – ${title}`,a);await notify('einnahmen',{typ:'Auftrag',text:`Auftrag ${no} – ${title}`,betrag:a,gebucht_von:currentName()})})}
async function saveDonation(){let a=requirePositive('donAmount','Spendenbetrag');confirmBook(`Spende über ${money(a)} von ${currentName()}. Zweck: Spende für Clan.`,async()=>{await q(T.don,'insert',{mitarbeiter_id:S.user.id,betrag:a,zweck:'Spende für Clan',created_at:new Date().toISOString()});await addProtocol('Spende',`Spende von ${currentName()}`,a);await notify('einnahmen',{typ:'Spende',text:`Spende für Clan von ${currentName()}`,betrag:a,gebucht_von:currentName()})})}
async function saveIncome(){let a=requirePositive('otherIncomeAmount','Betrag'),note=val('otherIncomeNote');if(!note)throw Error('Zweck/Notiz fehlt.');confirmBook(`Sonstige Einnahme ${money(a)} – ${note}`,async()=>{await q(T.book,'insert',{typ:'einnahme',betrag:a,beschreibung:note,gebucht_von:S.user.id,created_at:new Date().toISOString()});await addProtocol('Einnahme',note,a);await notify('einnahmen',{typ:'Sonstige Einnahme',text:note,betrag:a,gebucht_von:currentName()})})}
async function saveDeposit(){let a=requirePositive('depositAmount','Einzahlung'),note=val('depositNote')||'Einzahlung';confirmBook(`Einzahlung ${money(a)} – ${note}`,async()=>{await q(T.book,'insert',{typ:'einnahme',betrag:a,beschreibung:note,gebucht_von:S.user.id,created_at:new Date().toISOString()});await addProtocol('Einzahlung',note,a);await notify('einnahmen',{typ:'Einzahlung',text:note,betrag:a,gebucht_von:currentName()})})}
async function saveSalary(){if(!isSL())throw Error('Nur Stadtleitung darf Monatsgehälter auszahlen.');let emp=val('salaryEmployee'),m=val('salaryMonth'),a=requirePositive('salaryAmount','Gehalt');if(!m)throw Error('Monat fehlt.');confirmBook(`Monatsgehalt ${money(a)} für ${fmtPerson(emp)} (${m}).`,async()=>{await q(T.pay,'insert',{typ:'monatsgehalt',mitarbeiter_id:emp,betrag:a,monat:m,zweck:`Monatsgehalt ${m}`,gebucht_von:S.user.id,created_at:new Date().toISOString()});await addProtocol('Auszahlung',`Monatsgehalt ${m} für ${fmtPerson(emp)}`,a);await notify('auszahlungen',{typ:'Monatsgehalt',text:`${fmtPerson(emp)} – ${m}`,betrag:a,gebucht_von:currentName()})})}
async function savePayout(){let a=requirePositive('otherPayoutAmount','Betrag'),note=val('otherPayoutNote');if(!note)throw Error('Zweck/Notiz fehlt.');confirmBook(`Sonstige Auszahlung ${money(a)} – ${note}`,async()=>{await q(T.pay,'insert',{typ:'sonstige',betrag:a,zweck:note,gebucht_von:S.user.id,created_at:new Date().toISOString()});await addProtocol('Auszahlung',note,a);await notify('auszahlungen',{typ:'Sonstige Auszahlung',text:note,betrag:a,gebucht_von:currentName()})})}
async function savingsMove(direction){let id=direction==='in'?'saveToSavingsAmount':'fromSavingsAmount',a=requirePositive(id,'Betrag');confirmBook(`${direction==='in'?'Umbuchung aufs':'Umbuchung vom'} Sparkonto: ${money(a)}. Gesamtvermögen bleibt unverändert.`,async()=>{await q(T.save,'insert',{richtung:direction==='in'?'einzahlung':'auszahlung',betrag:a,gebucht_von:S.user.id,created_at:new Date().toISOString()});await addProtocol('Sparkonto',direction==='in'?`Auf Sparkonto: ${money(a)}`:`Vom Sparkonto: ${money(a)}`,a)})}
async function approveLoan(){if(!isSL())throw Error('Nur Stadtleitung darf Darlehen genehmigen.');let member=val('loanMember'),p=requirePositive('loanPrincipal','Ursprungsbetrag'),rate=n(val('loanRate')),mode=val('loanMode'),inst=n(val('loanInstallment')),due=val('loanDue');if(rate<0||rate>30)throw Error('Zinssatz muss zwischen 0 und 30 % liegen.');if(mode==='woechentlich'&&(inst<=0||!due))throw Error('Für wöchentliche Raten werden Rate und erste Fälligkeit benötigt.');let active=S.loans.filter(l=>l.mitglied_id===member&&['offen','ueberfaellig'].includes(l.status));if(active.length)throw Error('Dieses Mitglied hat bereits ein aktives Darlehen.');let interest=p*rate/100,total=p+interest;confirmBook(`Darlehen ${money(p)} genehmigen. Gesamtrückzahlung: ${money(total)}.`,async()=>{let l=(await q(T.loan,'insert',{mitglied_id:member,ursprungsbetrag:p,zinssatz:rate,zinssumme:interest,gesamtrueckzahlung:total,rueckzahlungsart:mode,woechentliche_rate:mode==='woechentlich'?inst:null,naechste_faelligkeit:mode==='woechentlich'?due:null,genehmigt_von:S.user.id,genehmigt_at:new Date().toISOString(),status:'offen'}))[0];if(mode==='woechentlich'){let count=Math.ceil(total/inst),left=total;for(let i=1;i<=count;i++){let amount=i===count?left:inst;left-=amount;let d=new Date(due);d.setDate(d.getDate()+7*(i-1));await q(T.rate,'insert',{darlehen_id:l.id,nummer:i,betrag:amount,faellig_am:d.toISOString().slice(0,10),status:'offen'});}}await addProtocol('Darlehen',`Darlehen für ${fmtPerson(member)}`,p);await notify('geldverleih',{typ:'Darlehen genehmigt',text:`${fmtPerson(member)} · ${money(p)} · ${rate}%`,betrag:p,gebucht_von:currentName()})})}
async function payRate(){let rid=val('myRate');let r=S.rates.find(x=>String(x.id)===String(rid));if(!r)throw Error('Keine offene Rate ausgewählt.');let l=S.loans.find(x=>x.id===r.darlehen_id);if(!l||l.mitglied_id!==S.user.id)throw Error('Du kannst nur deine eigenen Raten einzahlen.');confirmBook(`Rate ${r.nummer} über ${money(r.betrag)}. Bitte bestätige, dass der Betrag vorher ingame über /Clan bezahlt wurde.`,async()=>{await q(T.rate,'insert',{darlehen_id:l.id,nummer:r.nummer,betrag:r.betrag,faellig_am:r.faellig_am,status:'bezahlt',eingezahlt_von:S.user.id,eingezahlt_at:new Date().toISOString(),original_rate_id:r.id});await addProtocol('Darlehensrate',`Rate ${r.nummer} von ${currentName()}`,r.betrag);await notify('geldverleih',{typ:'Rate eingezahlt',text:`${currentName()} · Rate ${r.nummer}`,betrag:r.betrag,gebucht_von:currentName()})})}
async function notify(fn,payload){let d=db();if(!d)return;try{await d.functions.invoke(fn,{body:payload})}catch(e){console.warn('Discord',fn,e)}}
function totals(){let inc=0,exp=0,wages=0,wealth=0,sav=0,openLoans=0,fees=0,interestDue=0;S.orders.forEach(o=>{let a=n(o.auftragssumme);inc+=a;wealth+=a});S.don.forEach(x=>{inc+=n(x.betrag);wealth+=n(x.betrag)});S.book.forEach(x=>{if(x.typ==='einnahme'){inc+=n(x.betrag);wealth+=n(x.betrag)}else if(x.typ==='auszahlung'){exp+=n(x.betrag)}});S.pay.forEach(x=>{exp+=n(x.betrag);if(x.typ==='monatsgehalt'||x.typ==='auftragslohn')wages+=n(x.betrag)});S.save.forEach(x=>{sav+=(x.richtung==='einzahlung'?n(x.betrag):-n(x.betrag))});S.loans.forEach(l=>{if(['offen','ueberfaellig'].includes(l.status)){openLoans+=n(l.offener_betrag??l.gesamtrueckzahlung);if(l.naechste_faelligkeit&&l.naechste_faelligkeit<today())interestDue+=n(l.zinssumme)}});S.warnings.forEach(w=>fees+=n(w.gebuehr));wealth+=S.rates.filter(r=>r.status==='bezahlt').reduce((a,r)=>a+n(r.betrag),0)+fees;inc+=fees;return{inc,exp,wages,sav,wealth,openLoans,fees,interestDue}}
function available(t){let v=t.inc-t.exp;return v}
function renderOverview(){let t=totals(),av=available(t);$('vAvailable').textContent=money(av);$('vWealth').textContent=money(t.wealth);$('vIncome').textContent=money(t.inc);$('vExpenses').textContent=money(t.exp);$('vWages').textContent=money(t.wages);$('vSavings').textContent=money(t.sav);$('vLoans').textContent=money(t.openLoans);$('vInterestDue').textContent=money(t.interestDue);$('vFees').textContent=money(t.fees);$('cAvailable').textContent=money(av);$('cSavings').textContent=money(t.sav);$('cLoans').textContent=money(t.openLoans);let over=S.rates.filter(r=>r.status==='offen'&&r.faellig_am<today()).length;$('cOverdue').textContent=over;$('controlSummary').innerHTML=over?`<span class="red">${over} überfällige Rate(n).</span> Mahnungen müssen geprüft werden.`:'<span class="green">Keine überfälligen Raten erkannt.</span>'}
function renderLists(){let inc=[...S.don.map(x=>({d:x.created_at,t:'Spende',a:x.betrag,s:x.zweck})),...S.book.filter(x=>x.typ==='einnahme').map(x=>({d:x.created_at,t:'Einnahme',a:x.betrag,s:x.beschreibung}))].sort((a,b)=>new Date(b.d)-new Date(a.d)).slice(0,20);$('incomeList').innerHTML=inc.length?inc.map(x=>`<div class="tablewrap" style="margin:5px 0"><div style="padding:9px"><b class="green">+${money(x.a)}</b> · ${esc(x.t)} · ${esc(x.s||'')} <span class="muted">${dt(x.d)}</span></div></div>`).join(''):'<span class="muted">Keine Einnahmen.</span>';let po=S.pay.slice().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,20);$('payoutList').innerHTML=po.length?po.map(x=>`<div style="padding:9px;border-bottom:1px solid #292516"><b class="red">-${money(x.betrag)}</b> · ${esc(x.zweck||x.typ)} · ${esc(fmtPerson(x.mitarbeiter_id))} <span class="muted">${dt(x.created_at)}</span></div>`).join(''):'<span class="muted">Keine Auszahlungen.</span>';let sv=S.save.slice().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));$('savingsValue').textContent=money(totals().sav);$('savingsList').innerHTML=sv.slice(0,20).map(x=>`<div style="padding:8px;border-bottom:1px solid #292516">${x.richtung==='einzahlung'?'+':'-'}${money(x.betrag)} · ${dt(x.created_at)}</div>`).join('')||'<span class="muted">Keine Umbuchungen.</span>'}
function renderLoans(){let list=S.loans.slice().sort((a,b)=>new Date(b.genehmigt_at)-new Date(a.genehmigt_at));$('loanList').innerHTML=list.length?list.map(l=>{let rr=S.rates.filter(r=>r.darlehen_id===l.id),paid=rr.filter(r=>r.status==='bezahlt').reduce((a,r)=>a+n(r.betrag),0),open=n(l.gesamtrueckzahlung)-paid,over=rr.filter(r=>r.status==='offen'&&r.faellig_am<today()).length;return `<div class="panel" style="margin:8px 0"><b>${esc(fmtPerson(l.mitglied_id))}</b> · <span class="pill">${esc(l.status||'offen')}</span><br>Ursprung: ${money(l.ursprungsbetrag)} · Zins: ${n(l.zinssatz)}% · Gesamt: ${money(l.gesamtrueckzahlung)}<br>Bezahlt: ${money(paid)} · Offen: <b>${money(open)}</b> · Raten: ${rr.filter(r=>r.status==='offen').length} offen${over?` · <span class="red">${over} überfällig</span>`:''}<br><span class="muted">Genehmigt: ${dt(l.genehmigt_at)} von ${esc(fmtPerson(l.genehmigt_von))}</span></div>`}).join(''):'<span class="muted">Keine Darlehen.</span>';let mine=S.rates.filter(r=>r.status==='offen'&&S.loans.some(l=>l.id===r.darlehen_id&&l.mitglied_id===S.user.id));$('myRate').innerHTML=mine.map(r=>`<option value="${r.id}">Rate ${r.nummer} · ${money(r.betrag)} · fällig ${r.faellig_am}</option>`).join('')||'<option value="">Keine offene Rate</option>'}
function renderHistory(){let s=val('historySearch').toLowerCase(),type=val('historyType'),from=val('historyFrom'),to=val('historyTo'),rows=[];S.book.forEach(x=>rows.push({d:x.created_at,t:x.typ,a:x.betrag,desc:x.beschreibung||'',who:fmtPerson(x.gebucht_von)}));S.don.forEach(x=>rows.push({d:x.created_at,t:'Spende',a:x.betrag,desc:x.zweck,who:fmtPerson(x.mitarbeiter_id)}));S.pay.forEach(x=>rows.push({d:x.created_at,t:'Auszahlung',a:-x.betrag,desc:x.zweck||x.typ,who:fmtPerson(x.gebucht_von)}));S.orders.forEach(x=>rows.push({d:x.abschluss_at||x.created_at,t:'Auftrag',a:x.auftragssumme,desc:`${x.auftragsnummer} – ${x.titel}`,who:fmtPerson(x.gebucht_von)}));S.rates.filter(x=>x.status==='bezahlt').forEach(x=>rows.push({d:x.eingezahlt_at,t:'Darlehensrate',a:x.betrag,desc:`Rate ${x.nummer}`,who:fmtPerson(x.eingezahlt_von)}));rows.sort((a,b)=>new Date(b.d)-new Date(a.d));rows=rows.filter(x=>(!s||JSON.stringify(x).toLowerCase().includes(s))&&(!type||x.t===type||type==='einnahme'&&['Spende','einnahme'].includes(x.t)||type==='auszahlung'&&x.t==='Auszahlung'||type==='rate'&&x.t==='Darlehensrate')&&(!from||x.d?.slice(0,10)>=from)&&(!to||x.d?.slice(0,10)<=to));$('historyBody').innerHTML=rows.map(x=>`<tr><td>${dt(x.d)}</td><td>${esc(x.t)}</td><td class="${n(x.a)>=0?'green':'red'}">${n(x.a)>=0?'+':''}${money(x.a)}</td><td>${esc(x.desc)}</td><td>${esc(x.who)}</td><td>—</td></tr>`).join('')||'<tr><td colspan="6" class="muted">Keine Treffer.</td></tr>';S._history=rows}
function chart(target,kind){let now=new Date(),arr=[];for(let i=11;i>=0;i--){let d=new Date(now.getFullYear(),now.getMonth()-i,1),key=d.toISOString().slice(0,7),v=0;S.book.forEach(x=>{if(x.created_at?.slice(0,7)===key&&((kind==='in'&&x.typ==='einnahme')||(kind==='out'&&x.typ==='auszahlung')))v+=n(x.betrag)});S.don.forEach(x=>{if(kind==='in'&&x.created_at?.slice(0,7)===key)v+=n(x.betrag)});S.pay.forEach(x=>{if(kind==='out'&&x.created_at?.slice(0,7)===key)v+=n(x.betrag)});S.orders.forEach(x=>{if(kind==='in'&&(x.abschluss_at||x.created_at)?.slice(0,7)===key)v+=n(x.auftragssumme)});arr.push({key,v})}let max=Math.max(1,...arr.map(x=>x.v));$(target).innerHTML=arr.map(x=>`<div class="barcol"><i style="height:${Math.max(2,x.v/max*90)}%" title="${money(x.v)}"></i><span>${x.key.slice(5)}</span></div>`).join('');return arr}
function renderStats(){let a=chart('incomeChart','in'),b=chart('expenseChart','out'),ai=a.reduce((x,y)=>x+y.v,0),be=b.reduce((x,y)=>x+y.v,0);$('statsText').innerHTML=`Letzte 12 Monate:<br>Einnahmen: <b class="green">${money(ai)}</b><br>Ausgaben: <b class="red">${money(be)}</b><br>Differenz: <b>${money(ai-be)}</b>`}
function renderProtocols(){let p=S.protocol.slice().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));$('accountingProtocol').innerHTML=p.slice(0,40).map(x=>`<div style="padding:8px;border-bottom:1px solid #292516"><b>${esc(x.aktion||'Aktion')}</b> · ${esc(x.beschreibung||'')}<br><span class="muted">${dt(x.created_at)} · ${esc(fmtPerson(x.user_id))}</span></div>`).join('')||'<span class="muted">Keine Protokolle.</span>';let c=S.cash.slice().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));$('ingameProtocol').innerHTML=c.slice(0,40).map(x=>`<div style="padding:8px;border-bottom:1px solid #292516"><b>${esc(x.typ||'Kassenabgleich')}</b> · ${money(x.betrag||0)}<br><span class="muted">${dt(x.created_at)} · ${esc(fmtPerson(x.user_id||x.gebucht_von))}</span></div>`).join('')||'<span class="muted">Keine Ingame-Protokolle.</span>'}
function renderControl(){let checks=[];let t=totals();if(available(t)<0)checks.push('<span class="red">Aktuell verfügbar ist negativ.</span>');S.loans.filter(l=>['offen','ueberfaellig'].includes(l.status)).forEach(l=>{let over=S.rates.filter(r=>r.darlehen_id===l.id&&r.status==='offen'&&r.faellig_am<today()).length;if(over)checks.push(`<span class="red">${esc(fmtPerson(l.mitglied_id))}: ${over} überfällige Rate(n).</span>`)});if(!checks.length)checks.push('<span class="green">Alle Prüfungen unauffällig.</span>');$('controlChecks').innerHTML=checks.map(x=>`<div style="padding:9px;border-bottom:1px solid #292516">${x}</div>`).join('')}
function renderAll(){renderOverview();renderLists();renderLoans();renderHistory();renderStats();renderControl();if(S.me){employeeOptions('salaryEmployee');employeeOptions('loanMember');}if(!isSL())$('loanCreatePanel').classList.add('hidden')}
function csv(){let rows=S._history||[];let lines=[['Datum','Art','Betrag','Beschreibung','Von wem'],...rows.map(x=>[dt(x.d),x.t,x.a,x.desc,x.who])];let blob=new Blob(['\\ufeff'+lines.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='clanbuchhaltung_export.csv';a.click();URL.revokeObjectURL(a.href)}
function bind(){nav();$('refreshBtn').onclick=async()=>{try{await load();status('Aktuelle Daten geladen.','success')}catch(e){status(e.message,'error')}};$('addWorker').onclick=addWorker;['orderAmount','orderClan'].forEach(id=>$(id).addEventListener('input',orderPreview));$('orderWorkers').addEventListener('input',orderPreview);$('saveOrder').onclick=()=>saveOrder().catch(e=>status(e.message,'error'));$('saveDonation').onclick=()=>saveDonation().catch(e=>status(e.message,'error'));$('saveOtherIncome').onclick=()=>saveIncome().catch(e=>status(e.message,'error'));$('saveDeposit').onclick=()=>saveDeposit().catch(e=>status(e.message,'error'));$('saveSalary').onclick=()=>saveSalary().catch(e=>status(e.message,'error'));$('saveOtherPayout').onclick=()=>savePayout().catch(e=>status(e.message,'error'));$('saveToSavings').onclick=()=>savingsMove('in').catch(e=>status(e.message,'error'));$('fromSavings').onclick=()=>savingsMove('out').catch(e=>status(e.message,'error'));$('approveLoan').onclick=()=>approveLoan().catch(e=>status(e.message,'error'));$('payRate').onclick=()=>payRate().catch(e=>status(e.message,'error'));['historySearch','historyType','historyFrom','historyTo'].forEach(id=>$(id).addEventListener('input',renderHistory));$('exportCsv').onclick=csv;$('exportExcel').onclick=csv;$('confirmCancel').onclick=()=>{$('confirmModal').classList.remove('open');S.pending=null};$('confirmOk').onclick=runPending}
async function boot(){bind();try{await auth();await load();if(!S.loans.length)status('Buchhaltung geladen. Für Geldverleih müssen die V1-Tabellen einmal im Supabase-Projekt angelegt sein.','info')}catch(e){console.error(e);status(e.message||'Buchhaltung konnte nicht geladen werden.','error')}}
window.addEventListener('DOMContentLoaded',boot);
})();
