(() => {
"use strict";
const KEY="ehrenmarkt_clanbuchhaltung_v1_demo";
const TABLES={bookings:"buchhaltung_buchungen",savings:"buchhaltung_sparkonto",employees:"employees",orders:"buchhaltung_auftragsabrechnungen",workers:"buchhaltung_auftragsarbeiter",protocol:"buchhaltung_protokoll",cash:"buchhaltung_kassenabgleich",donations:"buchhaltung_spenden",payouts:"buchhaltung_auszahlungen",loans:"buchhaltung_darlehen",rates:"buchhaltung_darlehen_raten",warnings:"buchhaltung_darlehen_mahnungen"};
const state={mode:"demo",user:null,employee:{name:"Demo Mitarbeiter",rang:"Stadtleitung",user_id:null},employees:[],orders:[],income:[],payouts:[],savings:[],loans:[],rates:[],warnings:[],protocol:[],ingame:[]};
const $=id=>document.getElementById(id); const money=n=>`${Number(n||0).toLocaleString("de-DE",{maximumFractionDigits:2})} $`; const num=v=>{const n=Number(String(v??"").replace(",","."));return Number.isFinite(n)?n:0}; const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])); const dateNow=()=>new Date().toISOString(); const dateText=v=>v?new Date(v).toLocaleString("de-DE",{dateStyle:"short",timeStyle:"short"}):"—";
function saveLocal(){localStorage.setItem(KEY,JSON.stringify({orders:state.orders,income:state.income,payouts:state.payouts,savings:state.savings,loans:state.loans,rates:state.rates,warnings:state.warnings,protocol:state.protocol,ingame:state.ingame}));}
function loadLocal(){try{const x=JSON.parse(localStorage.getItem(KEY)||"{}");for(const k of ["orders","income","payouts","savings","loans","rates","warnings","protocol","ingame"])state[k]=Array.isArray(x[k])?x[k]:[];}catch{}}
function setStatus(msg,ok=true){const e=$("status");e.textContent=msg;e.className="status show "+(ok?"ok":"err");clearTimeout(setStatus.t);setStatus.t=setTimeout(()=>e.classList.remove("show"),5000)}
function rank(){return String(state.employee?.rang||"").toLowerCase()} function canManage(){return ["leitung","stadtleitung"].includes(rank())} function isCity(){return rank()==="stadtleitung"}
function employeeName(){return state.employee?.name||state.user?.user_metadata?.minecraft_name||state.user?.user_metadata?.username||state.user?.email||"Unbekannt"}
function totalOrderIncome(){return state.orders.reduce((s,o)=>s+num(o.amount),0)}
function totalOrderClan(){return state.orders.reduce((s,o)=>s+num(o.clan),0)}
function totalOrderWages(){return state.orders.reduce((s,o)=>s+num(o.wages),0)}
function totalIncome(){return totalOrderClan()+state.income.reduce((s,x)=>s+num(x.amount),0)+state.loans.reduce((s,l)=>s+num(l.paid),0)+state.warnings.reduce((s,w)=>s+num(w.fee),0)}
function totalExpenses(){return state.payouts.reduce((s,x)=>s+num(x.amount),0)+totalOrderWages()}
function savingsBalance(){return state.savings.reduce((s,x)=>s+(x.type==="Einzahlung"?num(x.amount):-num(x.amount)),0)}
function openLoanTotal(){return state.loans.reduce((s,l)=>s+(l.status==="Abgeschlossen"?0:num(l.open)),0)}
function totalWealth(){return totalIncome()}
function currentCash(){return totalIncome()-totalExpenses()-savingsBalance()}
function dueInterest(){return state.loans.filter(l=>l.status!=="Abgeschlossen").reduce((s,l)=>s+Math.max(0,num(l.total)-num(l.principal)-num(l.paid)),0)}
function lateFees(){return state.warnings.reduce((s,w)=>s+num(w.fee),0)}
function addProtocol(area,action,details,type="book"){const row={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:dateNow(),area,action,details,by:employeeName()};state.protocol.unshift(row);if(type==="ingame")state.ingame.unshift({...row,type:area,amount:details?.amount||0});saveLocal()}
async function invokeDiscord(fn,payload){try{const c=window.supabaseClient;if(!c?.functions?.invoke||state.mode!=="supabase")return;await c.functions.invoke(fn,{body:payload})}catch(e){console.warn("Discord",fn,e)}}
async function db(){return window.supabaseClient||null}
async function initSupabase(){const c=await db();if(!c){loadLocal();return}try{const {data:{user}}=await c.auth.getUser();state.user=user||null;if(!user){loadLocal();return}const {data:emp}=await c.from(TABLES.employees).select("user_id,name,rang,is_active").eq("user_id",user.id).maybeSingle();if(emp){state.employee=emp;state.mode="supabase";await loadSupabase(c);$("connectionText").textContent="Supabase verbunden";$("modeBadge").textContent="V1.0 LIVE";return}loadLocal()}catch(e){console.warn(e);loadLocal()}}
async function loadSupabase(c){const get=async(table)=>{try{const r=await c.from(table).select("*").order("created_at",{ascending:false});return r.error?[]:(r.data||[])}catch{return[]}};const [orders,bookings,savings,donations,payouts,loans,rates,warnings,logs]=await Promise.all([get(TABLES.orders),get(TABLES.bookings),get(TABLES.savings),get(TABLES.donations),get(TABLES.payouts),get(TABLES.loans),get(TABLES.rates),get(TABLES.warnings),get(TABLES.protocol)]);state.orders=orders.map(mapOrder);state.savings=savings.map(mapSaving);state.loans=loans.map(mapLoan);state.rates=rates;state.warnings=warnings;state.protocol=logs.map(mapProtocol);state.income=[...bookings.filter(b=>String(b.art||"").toLowerCase()==="einzahlung").map(b=>({id:b.id,date:b.datum||b.created_at,type:b.kategorie||"Einnahme",amount:b.betrag,from:b.von,purpose:b.zweck,by:b.erstellt_von_name})),...donations.map(mapDonation)];state.payouts=[...bookings.filter(b=>String(b.art||"").toLowerCase()==="auszahlung").map(b=>({id:b.id,date:b.datum||b.created_at,type:b.kategorie||"Auszahlung",amount:b.betrag,to:b.an,purpose:b.zweck,month:"",by:b.erstellt_von_name})),...payouts.map(mapPayout)];state.ingame=[...state.income,...state.payouts].map(x=>({date:x.date,type:x.type,amount:x.amount,area:x.type,by:x.by}));}
function mapOrder(o){return {id:o.id,no:o.auftragsnummer||o.order_number,title:o.auftragstitel||o.title||"Auftrag",amount:o.gesamtbetrag||o.amount,clan:o.clanbetrag||o.clan||0,wages:o.gesamt_gehaelter||o.wages||0,workers:[],date:o.datum||o.created_at,by:o.erstellt_von_name||o.created_by_name}}
function mapSaving(x){return {id:x.id,date:x.created_at||x.datum,type:x.art||x.typ,amount:x.betrag||x.amount,by:x.erstellt_von_name||x.von}}
function mapLoan(x){return {id:x.id,member:x.mitglied_name||x.member_name||x.mitglied_id,principal:x.originalbetrag||x.betrag||x.principal||0,interest:x.zinssatz||x.interest_rate||0,total:x.gesamtrueckzahlung||x.total_repayment||0,paid:x.bezahlt||x.paid||0,open:x.offen||x.open_amount||0,mode:x.rueckzahlungsart||x.repayment_mode||"",installment:x.wochenrate||x.weekly_installment||0,status:x.status||"Aktiv",date:x.genehmigt_am||x.created_at,by:x.genehmigt_von_name||x.created_by_name}}
function mapDonation(x){return {id:x.id,date:x.created_at,type:"Spende",amount:x.betrag||x.amount,from:x.mitarbeiter_name||x.von_name||x.mitarbeiter_id,purpose:"Spende für Clan",by:x.erstellt_von_name||x.mitarbeiter_name}}
function mapPayout(x){return {id:x.id,date:x.created_at,type:x.art||x.typ||"Auszahlung",amount:x.betrag||x.amount,to:x.mitarbeiter_name||x.mitarbeiter_id,purpose:x.zweck||x.purpose,month:x.monat||x.month,by:x.erstellt_von_name}}
function mapProtocol(x){return {id:x.id,date:x.created_at||x.datum,area:x.bereich||x.area,action:x.aktion||x.action,details:x.details||{},by:x.erstellt_von_name||x.erstellt_von}}
async function insert(table,payload){if(state.mode!=="supabase"){return {data:payload,error:null}}const c=await db();return c.from(table).insert(payload).select().single()}
function payloadBase(){return {created_at:dateNow(),user_id:state.user?.id||null,erstellt_von:state.user?.id||null,erstellt_von_name:employeeName()}}
function recalc(){$("currentBalance").textContent=money(currentCash());$("totalWealth").textContent=money(totalWealth());$("totalIncome").textContent=money(totalIncome());$("totalExpenses").textContent=money(totalExpenses());$("totalWages").textContent=money(totalOrderWages()+state.payouts.filter(x=>String(x.type).toLowerCase().includes("gehalt")).reduce((s,x)=>s+num(x.amount),0));$("savingsBalance").textContent=money(savingsBalance());$("savingBig").textContent=money(savingsBalance());$("openLoans").textContent=money(openLoanTotal());$("dueInterest").textContent=money(dueInterest());$("lateFees").textContent=money(lateFees());$("orderBy").textContent=employeeName();$("donationBy").value=employeeName();renderAll()}
function renderAll(){renderOrders();renderIncome();renderPayouts();renderSavings();renderLoans();renderProtocols();renderRecent();renderCharts();renderControl();fillEmployees();recalcSimple()}
function recalcSimple(){ $("totalIncome").textContent=money(totalIncome());$("totalExpenses").textContent=money(totalExpenses());$("totalWages").textContent=money(totalOrderWages()+state.payouts.filter(x=>String(x.type).toLowerCase().includes("gehalt")).reduce((s,x)=>s+num(x.amount),0));$("currentBalance").textContent=money(currentCash());$("totalWealth").textContent=money(totalWealth());$("savingsBalance").textContent=money(savingsBalance());$("savingBig").textContent=money(savingsBalance());$("openLoans").textContent=money(openLoanTotal());$("dueInterest").textContent=money(dueInterest());$("lateFees").textContent=money(lateFees());}
function renderOrders(){const q=( $("orderFilter")?.value||"").toLowerCase();const rows=state.orders.filter(o=>!q||`${o.no} ${o.title}`.toLowerCase().includes(q));$("ordersBody").innerHTML=rows.length?rows.map(o=>`<tr><td>${esc(o.no)}</td><td>${esc(o.title)}</td><td>${money(o.amount)}</td><td>${money(o.wages)}</td><td>${money(o.clan)}</td><td>${money(num(o.amount)-num(o.wages)-num(o.clan))}</td><td>${dateText(o.date)}</td><td>${esc(o.by)}</td></tr>`).join(""):`<tr><td colspan="8" class="empty">Noch keine Aufträge.</td></tr>`}
function renderIncome(){const rows=state.income.slice().sort((a,b)=>new Date(b.date)-new Date(a.date));$("incomeBody").innerHTML=rows.length?rows.map(x=>`<tr><td>${dateText(x.date)}</td><td>${esc(x.type)}</td><td class="green">${money(x.amount)}</td><td>${esc(x.from)}</td><td>${esc(x.purpose)}</td><td>${esc(x.by)}</td></tr>`).join(""):`<tr><td colspan="6" class="empty">Noch keine Einnahmen.</td></tr>`}
function renderPayouts(){const rows=state.payouts.slice().sort((a,b)=>new Date(b.date)-new Date(a.date));$("payoutBody").innerHTML=rows.length?rows.map(x=>`<tr><td>${dateText(x.date)}</td><td>${esc(x.type)}</td><td class="redtxt">${money(x.amount)}</td><td>${esc(x.to)}</td><td>${esc(x.purpose)}</td><td>${esc(x.month)}</td><td>${esc(x.by)}</td></tr>`).join(""):`<tr><td colspan="7" class="empty">Noch keine Auszahlungen.</td></tr>`}
function renderSavings(){const rows=state.savings.slice().sort((a,b)=>new Date(b.date)-new Date(a.date));$("savingBody").innerHTML=rows.length?rows.map(x=>`<tr><td>${dateText(x.date)}</td><td>${esc(x.type)}</td><td>${money(x.amount)}</td><td>${esc(x.by)}</td><td>${x.type==="Einzahlung"?"Sparkonto":"Clan-Kasse"}</td><td>${esc(x.by)}</td></tr>`).join(""):`<tr><td colspan="6" class="empty">Noch keine Sparkonto-Bewegungen.</td></tr>`}
function renderLoans(){const rows=state.loans;$("loanBody").innerHTML=rows.length?rows.map(l=>{const warns=state.warnings.filter(w=>w.loanId===l.id).length;return `<tr><td>${esc(l.member)}</td><td>${money(l.principal)}</td><td>${money(l.total)}</td><td>${money(l.paid)}</td><td>${money(l.open)}</td><td>${money(l.installment)}</td><td>${warns}/4</td><td>${esc(l.status)}</td></tr>`}).join(""):`<tr><td colspan="8" class="empty">Noch keine Darlehen.</td></tr>`}
function renderProtocols(){const b=state.protocol;$("bookBody").innerHTML=b.length?b.slice(0,100).map(x=>`<tr><td>${dateText(x.date)}</td><td>${esc(x.area)}</td><td>${esc(x.action)}</td><td>${esc(JSON.stringify(x.details))}</td><td>${esc(x.by)}</td></tr>`).join(""):`<tr><td colspan="5" class="empty">Noch kein Buchhaltungs-Protokoll.</td></tr>`;const i=state.ingame;$("ingameBody").innerHTML=i.length?i.slice(0,100).map(x=>`<tr><td>${dateText(x.date)}</td><td>${esc(x.type)}</td><td>${money(x.amount)}</td><td>${esc(x.area)}</td><td>${esc(x.by)}</td></tr>`).join(""):`<tr><td colspan="5" class="empty">Noch kein Ingame-Protokoll.</td></tr>`}
function renderRecent(){const all=[...state.income.map(x=>({...x,sign:"+"})),...state.payouts.map(x=>({...x,sign:"-"})),...state.savings.map(x=>({...x,sign:"↔"}))].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,8);$("recentBody").innerHTML=all.length?all.map(x=>`<tr><td>${dateText(x.date)}</td><td>${esc(x.type)}</td><td class="${x.sign==="+"?"green":x.sign==="-"?"redtxt":"gold"}">${x.sign} ${money(x.amount)}</td><td>${esc(x.purpose||x.by||"")}</td></tr>`).join(""):`<tr><td colspan="4" class="empty">Noch keine Buchungen.</td></tr>`}
function monthData(year){return Array.from({length:12},(_,m)=>{const inc=state.income.filter(x=>new Date(x.date).getFullYear()===year&&new Date(x.date).getMonth()===m).reduce((s,x)=>s+num(x.amount),0)+state.orders.filter(x=>new Date(x.date).getFullYear()===year&&new Date(x.date).getMonth()===m).reduce((s,x)=>s+num(x.clan),0)+state.loans.filter(x=>new Date(x.date).getFullYear()===year&&new Date(x.date).getMonth()===m).reduce((s,x)=>s+num(x.paid),0);const exp=state.payouts.filter(x=>new Date(x.date).getFullYear()===year&&new Date(x.date).getMonth()===m).reduce((s,x)=>s+num(x.amount),0)+state.orders.filter(x=>new Date(x.date).getFullYear()===year&&new Date(x.date).getMonth()===m).reduce((s,x)=>s+num(x.wages),0);return {inc,exp,label:["Jan","Feb","Mär","Apr","Mai","Jun","Jul","Aug","Sep","Okt","Nov","Dez"][m]}})}
function drawChart(el,data){if(!el)return;const max=Math.max(1,...data.map(x=>Math.max(x.inc,x.exp)));el.innerHTML=data.map(x=>`<div class="barcol"><b>${money(x.inc)}</b><i style="height:${Math.max(2,x.inc/max*75)}%"></i><span>${x.label}</span></div>`).join("")}
function renderCharts(){const year=new Date().getFullYear();drawChart($("overviewChart"),monthData(year));const years=[...new Set([year,...state.income.map(x=>new Date(x.date).getFullYear()),...state.orders.map(x=>new Date(x.date).getFullYear())])].sort();$("statsYear").innerHTML=years.map(y=>`<option>${y}</option>`).join("");drawChart($("statsChart"),monthData(Number($("statsYear").value||year)));const d=monthData(Number($("statsYear").value||year));$("yearIncome").textContent=money(d.reduce((s,x)=>s+x.inc,0));$("yearExpenses").textContent=money(d.reduce((s,x)=>s+x.exp,0));$("yearWages").textContent=money(state.orders.filter(x=>new Date(x.date).getFullYear()===Number($("statsYear").value||year)).reduce((s,x)=>s+num(x.wages),0));$("yearCount").textContent=String(state.income.filter(x=>new Date(x.date).getFullYear()===Number($("statsYear").value||year)).length)}
function renderControl(){const warnings=[];if(currentCash()<0)warnings.push("Aktuell verfügbar ist negativ.");for(const l of state.loans){if(l.status!=="Abgeschlossen"&&num(l.open)>0&&state.warnings.filter(w=>w.loanId===l.id).length>=4)warnings.push(`Darlehen von ${l.member} hat 4 Mahnungen erreicht.`)}$("controlGrid").innerHTML=[['Kassenstand',currentCash()<0],['Sparkonto',savingsBalance()<0],['Darlehen',state.loans.some(l=>num(l.open)<0)],['Aufträge',state.orders.some(o=>num(o.amount)-num(o.wages)-num(o.clan)<0)],['Protokolle',false],['Rechte',false]].map(([x,b])=>`<div class="item"><b>${esc(x)}</b><span class="${b?'warn':'ok'}">${b?'⚠ Prüfung nötig':'✓ OK'}</span></div>`).join("");$("controlWarnings").innerHTML=warnings.length?warnings.map(x=>`<div class="warning">⚠️ ${esc(x)}</div>`).join(""): `<div class="warning" style="border-color:rgba(101,213,139,.25);color:#a8efbd">✓ Keine auffälligen Zustände erkannt.</div>`}
function fillEmployees(){const emps=state.employees.length?state.employees:[state.employee];for(const id of ["salaryEmployee","loanMember"]){const e=$(id);if(e)e.innerHTML=emps.map(x=>`<option value="${esc(x.user_id||x.id||x.name)}">${esc(x.name||x.username||x.user_id)}</option>`).join("")}$("employeeText").textContent=`Rang: ${state.employee?.rang||"—"} · ${employeeName()}`}
function workerRow(){const wrap=$("workerRows");const row=document.createElement("div");row.style.cssText="display:grid;grid-template-columns:1fr 150px auto;gap:8px;margin:7px 0";row.innerHTML=`<input class="worker-name" placeholder="Mitarbeiter"><input class="worker-salary" type="number" min="0" placeholder="Gehalt"><button type="button" class="btn small">×</button>`;row.querySelector("button").onclick=()=>{row.remove();updateRest()};wrap.appendChild(row);row.querySelectorAll("input").forEach(i=>i.addEventListener("input",updateRest))}
function workers(){return [...document.querySelectorAll("#workerRows>div")].map(r=>({name:r.querySelector(".worker-name")?.value.trim(),salary:num(r.querySelector(".worker-salary")?.value)})).filter(x=>x.name)}
function updateRest(){const total=num($("orderAmount").value),clan=num($("orderClan").value),w=workers().reduce((s,x)=>s+x.salary,0);$("orderRest").textContent=money(total-clan-w)}
async function saveOrder(){if(!canManage()){setStatus("Nur Leitung und Stadtleitung dürfen Aufträge erfassen.",false);return}const no=$("orderNo").value.trim(),title=$("orderTitle").value.trim(),amount=num($("orderAmount").value),clan=num($("orderClan").value),ws=workers(),wages=ws.reduce((s,x)=>s+x.salary,0),rest=amount-clan-wages;if(!no||!title||amount<=0||clan<0||rest<0){setStatus("Bitte Auftragsdaten und Verteilung prüfen.",false);return}const row={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),no,title,amount,clan,wages,workers:ws,date:dateNow(),by:employeeName()};if(state.mode==="supabase"){const p={...payloadBase(),auftragsnummer:no,auftragstitel:title,gesamtbetrag:amount,clanbetrag:clan,gesamt_gehaelter:wages,datum:row.date,status:"Abgeschlossen"};const r=await insert(TABLES.orders,p);if(r.error){setStatus(r.error.message,false);return}row.id=r.data.id}state.orders.unshift(row);addProtocol("Auftrag","Abgeschlossen",{number:no,amount,clan,wages});if(clan>0){const inc={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:row.date,type:"Auftrag",amount:clan,from:"Auftrag",purpose:`Clan-Anteil ${no}`,by:employeeName()};state.income.unshift(inc);state.ingame.unshift({...inc,area:"Auftrag"});await invokeDiscord("einnahmen",{title:"💰 Auftrag abgeschlossen",type:"Auftrags-Einnahme",amount:clan,from:"Auftrag",purpose:inc.purpose,orderNumber:no,status:"Abgeschlossen",createdBy:employeeName(),date:row.date})}state.payouts.push(...ws.map(x=>({id:String(Date.now())+x.name,date:row.date,type:"Auftragsgehalt",amount:x.salary,to:x.name,purpose:`Gehalt Auftrag ${no}`,month:"",by:employeeName()})));await invokeDiscord("auszahlungen",{title:"💸 Auftragsgehälter",type:"Auftragsgehalt",amount:wages,to:ws.map(x=>x.name).join(", "),purpose:`Auftrag ${no}`,orderNumber:no,status:"Erfasst",createdBy:employeeName(),date:row.date});saveLocal();$("orderConfirm").classList.remove("show");$("orderForm").reset();$("workerRows").innerHTML="";workerRow();recalc();setStatus("Auftrag erfolgreich und endgültig gespeichert.")}
async function saveDonation(){const amount=num($("donationAmount").value);if(amount<=0){setStatus("Bitte einen gültigen Spendenbetrag eingeben.",false);return}const row={id:String(Date.now()),date:dateNow(),type:"Spende",amount,from:employeeName(),purpose:"Spende für Clan",by:employeeName()};if(state.mode==="supabase"){const r=await insert(TABLES.donations,{...payloadBase(),mitarbeiter_id:state.employee?.user_id||state.user?.id,betrag:amount});if(r.error){setStatus(r.error.message,false);return}row.id=r.data.id}state.income.unshift(row);state.ingame.unshift({...row,area:"Spende"});addProtocol("Einnahme","Spende",row);await invokeDiscord("einnahmen",{title:"💵 Neue Spende",type:"Spende",amount,from:employeeName(),purpose:"Spende für Clan",status:"Erfasst",createdBy:employeeName(),date:row.date});saveLocal();$("donationAmount").value="";$("donationConfirm").classList.remove("show");recalc();setStatus("Spende gespeichert.")}
async function saveOtherIncome(){const amount=num($("otherIncomeAmount").value),purpose=$("otherIncomePurpose").value.trim();if(amount<=0||!purpose){setStatus("Betrag und Zweck sind erforderlich.",false);return}const row={id:String(Date.now()),date:dateNow(),type:"Sonstige Einnahme",amount,from:"Clan-Einnahme",purpose,by:employeeName()};state.income.unshift(row);state.ingame.unshift({...row,area:"Einnahme"});addProtocol("Einnahme","Sonstige Einnahme",row);await invokeDiscord("einnahmen",{title:"💵 Sonstige Einnahme",type:"Sonstige Einnahme",amount,from:"Clan-Einnahme",purpose,status:"Erfasst",createdBy:employeeName(),date:row.date});saveLocal();$("otherIncomeAmount").value="";$("otherIncomePurpose").value="";$("incomeConfirm").classList.remove("show");recalc();setStatus("Einnahme gespeichert.")}
async function savePayout(type,to,amount,purpose,month=""){if(!canManage()){setStatus("Nur Leitung und Stadtleitung dürfen Auszahlungen erfassen.",false);return}if(amount<=0||!purpose){setStatus("Betrag und Zweck sind erforderlich.",false);return}if(amount>currentCash()){setStatus("Die Auszahlung überschreitet den aktuell verfügbaren Clanbestand.",false);return}const row={id:String(Date.now()),date:dateNow(),type,amount,to,purpose,month,by:employeeName()};state.payouts.unshift(row);state.ingame.unshift({...row,area:"Auszahlung"});addProtocol("Auszahlung",type,row,"ingame");await invokeDiscord("auszahlungen",{title:"💸 Neue Auszahlung",type,amount,to,purpose,month,status:"Erfasst",createdBy:employeeName(),date:row.date});saveLocal();recalc();setStatus("Auszahlung gespeichert.")}
async function saveSaving(){const type=$("savingType").value,amount=num($("savingAmount").value);if(amount<=0||type==="Auszahlung"&&amount>savingsBalance()){setStatus("Ungültiger Sparkonto-Betrag.",false);return}const row={id:String(Date.now()),date:dateNow(),type,amount,by:employeeName()};state.savings.unshift(row);addProtocol("Sparkonto",type,row,"ingame");saveLocal();$("savingAmount").value="";recalc();setStatus("Sparkonto-Umbuchung gespeichert.")}
async function saveLoan(){if(!isCity()){setStatus("Nur Stadtleitung darf Darlehen genehmigen.",false);return}const member=$("loanMember").selectedOptions[0]?.text||"Mitglied",principal=num($("loanAmount").value),interest=num($("loanInterest").value),mode=$("loanMode").value,installment=num($("loanInstallment").value);if(principal<=0||interest<0||interest>30||(mode.includes("Wöchent")&&installment<=0)){setStatus("Bitte Darlehensdaten prüfen.",false);return}if(state.loans.some(l=>l.member===member&&l.status!=="Abgeschlossen")){setStatus("Dieses Mitglied hat bereits ein aktives Darlehen.",false);return}const total=principal*(1+interest/100);const row={id:String(Date.now()),member,principal,interest,total,paid:0,open:total,mode,installment,status:"Aktiv",date:dateNow(),by:employeeName()};state.loans.unshift(row);addProtocol("Geldverleih","Darlehen genehmigt",row,"ingame");await invokeDiscord("geldverleih",{title:"💰 Darlehen genehmigt",type:"Darlehen",amount:principal,member,interest,totalRepayment:total,paid:0,openAmount:total,status:"Aktiv",createdBy:employeeName(),description:`Rückzahlungsart: ${mode}`});saveLocal();recalc();setStatus("Darlehen erfasst.")}
function testBooking(){const now=dateNow();const order={id:"TEST-"+Date.now(),no:"TEST-001",title:"V1 Funktionstest",amount:1000000,clan:600000,wages:400000,workers:[{name:"Testarbeiter",salary:400000}],date:now,by:"V1 Test"};state.orders.unshift(order);state.income.unshift({id:"TEST-IN",date:now,type:"Test-Auftrag",amount:600000,from:"Testauftrag",purpose:"V1 Test",by:"V1 Test"});state.payouts.unshift({id:"TEST-OUT",date:now,type:"Test-Gehalt",amount:400000,to:"Testarbeiter",purpose:"V1 Test",month:"",by:"V1 Test"});addProtocol("Test","Testbuchung",order,"ingame");saveLocal();recalc();setStatus("🧪 Test erfolgreich: 1.000.000 $ Auftrag, 600.000 $ Clan-Anteil und 400.000 $ Gehalt wurden lokal erfasst.")}
function exportCsv(){if(!canManage()){setStatus("CSV-Export ist nur für Leitung und Stadtleitung vorgesehen.",false);return}const rows=[...state.income.map(x=>[x.date,"Einnahme",x.amount,x.purpose,x.by]),...state.payouts.map(x=>[x.date,"Auszahlung",-x.amount,x.purpose,x.by]),...state.orders.map(x=>[x.date,"Auftrag",x.clan,`Clan-Anteil ${x.no}`,x.by])];const csv="Datum;Art;Betrag;Zweck;Eingetragen von\n"+rows.map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download="clanbuchhaltung-export.csv";a.click();URL.revokeObjectURL(a.href)}
function nav(){document.querySelectorAll("#nav button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("#nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".section").forEach(s=>s.classList.remove("active"));$("section-"+b.dataset.section).classList.add("active");$("pageTitle").textContent=b.textContent.trim();window.scrollTo({top:0,behavior:"smooth"})}))}
function bind(){nav();$("addWorker").onclick=workerRow;workerRow();["orderAmount","orderClan"].forEach(id=>$(id).addEventListener("input",updateRest));$("orderSave").onclick=()=>$("orderConfirm").classList.add("show");$("orderCancelConfirm").onclick=()=>$("orderConfirm").classList.remove("show");$("orderFinalSave").onclick=saveOrder;$("donationSave").onclick=()=>$("donationConfirm").classList.add("show");$("donationFinal").onclick=saveDonation;$("incomeSave").onclick=()=>$("incomeConfirm").classList.add("show");$("incomeFinal").onclick=saveOtherIncome;document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).classList.remove("show"));$("salarySave").onclick=()=>savePayout("Monatsgehalt",$("salaryEmployee").selectedOptions[0]?.text||"Mitarbeiter",num($("salaryAmount").value),"Monatsgehalt",$("salaryMonth").value);$("payoutSave").onclick=()=>savePayout("Sonstige Auszahlung","Clan",num($("otherPayoutAmount").value),$("otherPayoutPurpose").value.trim());$("savingSave").onclick=saveSaving;$("loanSave").onclick=saveLoan;$("testBtn").onclick=testBooking;$("exportBtn").onclick=exportCsv;$("reloadBtn").onclick=()=>{loadLocal();recalc();setStatus("Daten aktualisiert.")};$("orderFilter").oninput=renderOrders;$("statsYear").onchange=renderCharts;$("runControl").onclick=renderControl;document.querySelectorAll(".protocol-tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".protocol-tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("protoIngame").classList.toggle("hide",b.dataset.proto!=="ingame");$("protoBook").classList.toggle("hide",b.dataset.proto!=="book")})}
document.addEventListener("DOMContentLoaded",async()=>{loadLocal();bind();await initSupabase();fillEmployees();$("salaryMonth").value=new Date().toISOString().slice(0,7);recalc();setStatus(state.mode==="supabase"?"Supabase-Verbindung aktiv.":"V1.0 läuft im sicheren Demo-/Lokalmode. Testdaten werden nicht an Supabase gesendet.")});
})();